### PR TITLE
Externalize configuration #21

### PR DESCRIPTION
**Pull request by motofix**
The purpose of this enhancement is to be able to define the configuration outside the main php file. By default I have defined it to be in the same directory, but it is possible, and recommended, to put it in another place not accessible by a browser.

### CODE REVIEW

**Comment by softius** [comment]
Hi @motofix , I've been thinking this change for a while and I would like to see the configuration be de-coupled from the actual implementation. This would make the future updates more easier. However, I don't see any reason why the configuration should be in XML format; prefer plain PHP instead. Any reason why you have used XML in the first place?

**Comment by motofix** [comment]
Well I'm not a PHP expert, but the main idea was to be able to store the configuration really outside the "web php area". Using plain text / XML file appeared to be a good solution, [I'm storing it in /etc/xxx/proxy.conf.xml in my project](https://framagit.org/motofix/santeuil.com/blob/master/app/proxy.php#L49)
I'm using XML because I like structured data that would have all the tooling for manipulation / validation.

**Comment by softius** [comment]
I want to keep the final solution as simple as possible. As mentioned, I find the (plain) PHP configuration ideal. It's a simple set of configuration really (4-5 configuration entries) and chances are they will be configured only once and never changed.

**Comment by motofix** [comment]
Maybe the plain PHP file would not appears to be the most ideal / understandable solution for somebody who is not comfortable with this language ;-)
The XML have the advantage to be more "cross-language" way of structuring information, would it be for configuration or data exchange (JSON is also a good candidate I would say, despite the lack of easy tooling for validation / parsing in PHP).

**Comment by yarick123** [comment]
The problem with XML is not only additional complexity, as said @softius. In the standard apache httpd configuration, raw XML files are transferred to the client. If the configuration is in a PHP file, the raw content would normally not be sent to the client. So, adding XML configuration means security problems.
 Of course, the security problems can be solved by putting the XML file out of the web root or by extending the web server configuration. But this is additional time and headache.
  This is why, I see, that the configuration in a plain PHP file is better :)

**Pull request closed without merging**
